version: '3.8'
services:
  db:
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE

  phpmyadmin:
    image: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    depends_on:
      - db

  app:
    image: app:latest
    build:
      context: .
      dockerfile: ./.docker/dev.dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db

  migration:
    image: app:latest
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "run", "db:migrate"]
    depends_on:
      - db
